sudo: false
language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: KB9ef2UZyW0YRKc8YmEPtvn7Y49LJJPcTNSPMlpZetvMWLVYZzSkBwsZg2nkdAMeaYTmdkHYbsXbfy35FSY3+yCp3ULrmbRl/uQmviLBJC3CadKZBCx5236ZboCY10341AC5nMvfkcB7OJAoS6tN7EKU5IdWhPvK+6r1fl83fLw=
