version: 2
jobs:
  build-jdk8:
    docker:
      - image: openjdk:8u162-jdk-stretch
    steps:
      - run:
          name: update image
          command: apt-get update
      - run:
          name: install debian dependencies
          command: apt-get install -y openssl libssl-dev maven
      - checkout
      - restore_cache:
          key: v1-cache-xio-{{ arch }}-{{ checksum "pom.xml" }}
      - run:
          name: install maven dependencies
          command: mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true clean test-compile dependency:resolve-plugins dependency:go-offline
      - run:
          name: run tests
          command: mvn --batch-mode clean verify -DCOVERAGE=1
      - run:
          name: build package
          command: mvn --batch-mode package javadoc:jar
      - run:
          name: build reports
          command: mvn --batch-mode -pl xio-core coveralls:report -Dmaven.javadoc.skip=true -DrepoToken=${COVERALLS_REPO_TOKEN}
      - save_cache:
          key: v1-cache-xio-{{ arch }}-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
  build-jdk9:
    docker:
      - image: openjdk:9.0-jdk-sid
    steps:
      - run:
          name: update image
          command: apt-get update
      - run:
          name: install debian dependencies
          command: apt-get install -y openssl libssl-dev maven
      - checkout
      - run:
          name: install maven dependencies
          command: mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true clean test-compile dependency:resolve-plugins dependency:go-offline
      - run:
          name: run tests
          command: mvn --batch-mode clean verify -DCOVERAGE=1
      - run:
          name: build package
          command: mvn --batch-mode package javadoc:jar
  build-jdk10:
    docker:
      - image: openjdk:10-jdk
    steps:
      - run:
          name: update image
          command: apt-get update
      - run:
          name: install debian dependencies
          command: apt-get install -y openssl libssl-dev maven
      - checkout
      - run:
          name: install maven dependencies
          command: mvn --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true clean test-compile dependency:resolve-plugins dependency:go-offline
      - run:
          name: run tests
          command: mvn --batch-mode clean verify -DCOVERAGE=1
      - run:
          name: build package
          command: mvn --batch-mode package javadoc:jar

workflows:
  version: 2
  build:
    jobs:
      - build-jdk8
      - build-jdk9
      - build-jdk10
#  dependencies:
#    cache_directories:
#      - ~/.m2
#  test:
#    override:
#      - mvn clean verify -Dmaven.javadoc.skip=true -DCOVERAGE=1
#      - mvn package javadoc:jar -Dmaven.javadoc.skip=true
#      - mvn -pl xio-core coveralls:report -Dmaven.javadoc.skip=true -DrepoToken=${COVERALLS_REPO_TOKEN}
#    post:
#      - cp xio-core/target/xio*jar pom.xml $CIRCLE_ARTIFACTS
#      - mkdir -p $CIRCLE_TEST_REPORTS/junit/
#      - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
#  deployment:
#    main:
#      branch: master
#      commands:
#        - mvn -N io.takari:maven:wrapper
#        - ./mvnw -pl xio-core -P packagecloud -s .circleci.settings.xml -DskipTests deploy
