version: 2
jobs:
  build-jdk8:
    docker:
      - image: openjdk:8-jdk-stretch
    steps:
      - run:
          name: update image
          command: sudo apt-get update
      - run:
          name: install depdendencies
          command: sudo apt-get install openssl libssl-dev
workflows:
  version: 2
  build:
    jobs:
      - build-jdk8
#  dependencies:
#    cache_directories:
#      - ~/.m2
#    override:
#      - mvn -DskipTests=true -Dmaven.javadoc.skip=true clean test-compile dependency:resolve-plugins dependency:go-offline
#  test:
#    override:
#      - mvn clean verify -Dmaven.javadoc.skip=true -DCOVERAGE=1
#      - mvn package javadoc:jar -Dmaven.javadoc.skip=true
#      - mvn -pl xio-core coveralls:report -Dmaven.javadoc.skip=true -DrepoToken=${COVERALLS_REPO_TOKEN}
#    post:
#      - cp xio-core/target/xio*jar pom.xml $CIRCLE_ARTIFACTS
#      - mkdir -p $CIRCLE_TEST_REPORTS/junit/
#      - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
#  deployment:
#    main:
#      branch: master
#      commands:
#        - mvn -N io.takari:maven:wrapper
#        - ./mvnw -pl xio-core -P packagecloud -s .circleci.settings.xml -DskipTests deploy
